Added widget for members, and in other place for board
Inter-Actief/amelie pull request #700
Opened 2022-12-13 00:28 UTC by SimplyPancake

Please add the following information to your pull request:

**Please describe what your PR is fixing**
Fixing the issue to add the discord server widget to the website for logged in members

**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References Inter-Actief/amelie#<issue_id>`)**
#677 

**Does your PR change how we process personal data, impact our [privacy document](https://www.inter-actief.utwente.nl/privacy/), or modify (one of) our data export(s)?**
no

**Does your PR include any django migrations?**
no

**Does your PR include the proper translations (did you add translations for new/modified strings)?**
no, my PR does not include translations

**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` file)?**
no, my PR does not include CSS changes

**Does your PR need external actions by for example the System Administrators? (Think about new pip packages, new (local) settings, a new regular task or cronjob, new management commands, etc.)?**
no

**Did you properly test your PR before submitting it?**
yes

2022-12-13 11:30 UTC, Kurocon approved these changes

2022-12-13 12:33 UTC, WKobes requested changes

2022-12-13 12:33 UTC, WKobes commented on templates/frontpage.html
> +                {# End member view: discord page things #}
board view

2022-12-13 12:35 UTC, WKobes commented
What is the reason it is different for board and members?

2022-12-13 14:47 UTC, SimplyPancake commented on templates/frontpage.html
> +                {# End member view: discord page things #}
The reason that the board view is in a different spot, is that the horizantal space is used differently! Otherwise if the board is logged in, it would look a little ugly, but it is not necessary to have the board view of course

2022-12-13 15:50 UTC, WKobes commented on templates/frontpage.html
> +                {# End member view: discord page things #}
Check, this comment was about a typo in the comment line 270 (member > board)

2022-12-13 18:23 UTC, Kurocon commented
> What is the reason it is different for board and members?

First column on the front page would become very long otherwise

2023-01-23 19:07 UTC, Kurocon approved these changes

2023-01-23 19:07 UTC, merged