Make underage filter only accessible for board
Inter-Actief/amelie pull request #704
Opened 2022-12-19 14:49 UTC by Nierot

Please add the following information to your pull request:

**Please describe what your PR is fixing**
Change the functionality of the "only show underage participants" button on an activity page to only be available for board members.

**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References Inter-Actief/amelie#<issue_id>`)**
Fixes #697 

**Does your PR change how we process personal data, impact our [privacy document](https://www.inter-actief.utwente.nl/privacy/), or modify (one of) our data export(s)?**
Yes, but no. The button first gave more information than possible with our privacy policy, which has been fixed to be compliant again.

**Does your PR include any django migrations?**
no

**Does your PR include the proper translations (did you add translations for new/modified strings)?**
no, my PR does not include translations

**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` file)?**
no, my PR does not include CSS changes

**Does your PR need external actions by for example the System Administrators? (Think about new pip packages, new (local) settings, a new regular task or cronjob, new management commands, etc.)?**
no

**Did you properly test your PR before submitting it?**
no

2022-12-21 12:49 UTC, WKobes requested changes

2022-12-21 12:49 UTC, WKobes commented on amelie/activities/views.py
> +    only_show_underage = (request.GET.get('underage') == "True") and request.is_board
For efficiency, switch the and statement (request.is_board will most likely require less resources)

2023-01-19 13:05 UTC, bramvandartel approved these changes

2023-01-20 13:16 UTC, WKobes approved these changes

2023-01-23 18:24 UTC, Kurocon approved these changes

2023-01-23 19:13 UTC, merged