Implement event cancellation
Inter-Actief/amelie pull request #788
Opened 2023-09-18 20:58 UTC by supertom01

Please add the following information to your pull request:

**Please describe what your PR is fixing**
When an event was cancelled, the name of the event would just be prepended with CANCELLED or something similar. However, it is nicer (and more future-proof) to actually have a database entry for this. Additionally, the website will now automatically refund all transactions and send enrolled people an email.

This was made together with @Mihai98924, give this guy some kuddos. He deserves them!

**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References Inter-Actief/amelie#<issue_id>`)**
Fixes Inter-Actief/amelie#696

**Does your PR change how we process personal data, impact our [privacy document](https://www.inter-actief.utwente.nl/privacy/), or modify (one of) our data export(s)?**
no

**Does your PR include any django migrations?**
yes

**Does your PR include the proper translations (did you add translations for new/modified strings)?**
yes, I have included the translation

**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` file)?**
no, my PR does not include CSS changes

**Does your PR need external actions by for example the System Administrators? (Think about new pip packages, new (local) settings, a new regular task or cronjob, new management commands, etc.)?**
no

**Did you properly test your PR before submitting it?**
yes

2023-09-21 13:50 UTC, bramvandartel requested changes

2023-09-21 13:50 UTC, bramvandartel commented on amelie/activities/templates/activity.html
> +                                </a>
Combine this into the if statement before, such that this is always on the same spot.

2023-09-21 13:50 UTC, bramvandartel commented on amelie/activities/views.py
> +    if not obj.can_edit(request.person):
@require_board has been used already

2023-09-21 13:50 UTC, bramvandartel commented on amelie/activities/views.py
> +                transactions.participation_transaction(participation, "Cancelled event", cancel=True, added_by=request.person)
Please include the activity in the name of the transaction

2023-09-21 13:50 UTC, bramvandartel commented on amelie/activities/templates/activity.html
> +	                            <a class="looks-like-a-button icon icon-delete" href="{% url 'activities:delete' obj.id %}">{% trans 'Delete' %}</a>
Only allow deletion of an activity when it has no participants anymore, meaning that it should either:
1) be cancelled already
2) have no participations

Otherwise ghost transactions still occur.

Add this check in the backend as well.

2023-09-21 13:50 UTC, bramvandartel commented on amelie/activities/views.py
> +        messages.success(request, _(f"{obj} has been successfully re-opened. If you want people to enroll again, please open the enrollments manually."))
"Please note that all previous enrollments are not added again"

2023-09-21 18:58 UTC, Kurocon requested changes

2023-09-21 18:58 UTC, Kurocon commented on amelie/activities/mail.py
> +    if settings.DEBUG:
It's not necessary to make a distinction for debug mode here, because all mails in debug are redirected to a file on the server. So it's better to just generate the same message as normally, so you can test the functionality properly.

2023-09-21 18:58 UTC, Kurocon commented on amelie/activities/templates/activities/activity_cancelled.mail
> +{% with costs=participation.calculate_costs|first paymentmethod=participation.get_payment_method_display %}{% if costs > 0 %}{% htmlify %}{% blocktrans %}The total costs were {{ costs }} euro. These
~~These will be refunded.~~
These costs will be refunded on your personal tab.

Because, at the point of cancellation, the costs are not debited yet via direct debit.

2023-09-21 18:58 UTC, Kurocon commented on amelie/activities/templates/activity.html
> +                                {% if not obj.cancelled %}
Cancellation should only be possible if the event has not occurred yet (before the start date of the event). Otherwise costs may have already been deducted. So the button should also only show if the event has not happened yet.

2023-09-21 18:58 UTC, Kurocon commented on amelie/activities/views.py
> +    In the case of re-publishing, the event name will be reverted to its original name and enrollments will be re-openend.
Cancellation should only be possible if the event has not occurred yet (before the start date of the event). Otherwise costs may have already been deducted. This should be checked before cancelling, and a message should be shown if cancellation is not possible because the event already happened.

2023-09-21 18:58 UTC, Kurocon commented on locale/nl/LC_MESSAGES/django.po
> +msgstr "Annulering van"
Missing space at the end of the dutch string

2023-09-21 18:58 UTC, Kurocon commented on locale/nl/LC_MESSAGES/django.po
> +msgstr "{obj} is succesvol heropend. Als je wil dat mensen zich opnieuw aan kunnen melden, zet dit dan weer aan."
~~zich opnieuw aan kunnen melden, zet dit dan weer aan.~~
zich opnieuw kunnen inschrijven, zet de inschrijving dan handmatig weer open.

2023-09-21 18:58 UTC, Kurocon commented on locale/nl/LC_MESSAGES/django.po
> +msgstr "Of dit evenement geannuleerd is. Deelnemers ontvangen hiervan een email!"
"Annuleer een evenement alleen als dat nodig is." mist in de vertaling.

2023-09-22 18:59 UTC, Kurocon commented
Someone also just reminded me about people who might have already paid by cash, we need to handle those situations as well

2023-09-22 21:20 UTC, supertom01 commented
I've tackled the issue with cash payments that the treasurer will get an email with all the people that have paid in cash. Additionally, only people that have paid by mandate will get a transaction that refunds their money.

2023-10-16 18:58 UTC, Kurocon approved these changes
Found 1 unused template it seems, for the rest I think it looks good!

2023-10-16 18:58 UTC, Kurocon commented on amelie/activities/templates/activities/activity_cancelled_cash_participant.mail
Unused template?

2023-10-16 19:07 UTC, Kurocon approved these changes

2023-10-16 19:45 UTC, merged