GraphQL API (public parts)
Inter-Actief/amelie pull request #888
Opened 2024-09-02 18:47 UTC by Kurocon

Please add the following information to your pull request:

**Please describe what your PR is fixing**
Adds a GraphQL API for public resources.

**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References Inter-Actief/amelie#<issue_id>`)**
Fixes #741 

**Does your PR change how we process personal data, impact our [privacy document](https://www.inter-actief.utwente.nl/privacy/), or modify (one of) our data export(s)?**
no

**Does your PR include any django migrations?**
no

**Does your PR include the proper translations (did you add translations for new/modified strings)?**
yes, I have included the translations

**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` file)?**
no, my PR does not include CSS changes

**Does your PR need external actions by for example the System Administrators? (Think about new pip packages, new (local) settings, a new regular task or cronjob, new management commands, etc.)?**
no

**Did you properly test your PR before submitting it?**
yes

2024-09-02 20:04 UTC, Kurocon commented
Some (previously) private information is currently made public that we (probably) don't want:

ActivityType: (something seems to go wrong with the fields specification here as well)
- callbackUrl
- callbackSecretKey
- facebookEventId
- updateCount
- placesAvailable (only logged in)
- hasWaitingParticipants

CommitteeType:
- abbreviation

AttachmentType:
- non-public attachments are visible

WebsiteBannerType:
- startDate
- endDate
- Only active banners should be visible

TO BE CONTINUED, OUT OF TIME.

2024-09-02 21:38 UTC, Kurocon commented
We probably should also add unit tests for each attribute that is only shown when authenticated, to make sure it doesn't end HP being publicly available at a later point. Graphene has some facilities for this: https://docs.graphene-python.org/projects/django/en/latest/testing/

2024-12-09 20:57 UTC, Kurocon commented
As far as I can tell, the tests are as done as they could be for now.
So, this is ready for merging!

2024-12-17 09:30 UTC, supertom01 reviewed
Some very minor comments, but other than that good

2024-12-17 09:30 UTC, supertom01 commented on amelie/settings/local.py.default
> +DEBUG_TOOLBAR = True and "test" not in sys.argv
This makes the `True` value a bit unnecessary

2024-12-17 09:30 UTC, supertom01 commented on amelie/settings/local.py.localdev
> +DEBUG_TOOLBAR = True and "test" not in sys.argv
This makes the `True` value a bit unnecessary

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/__init__.py
> +        content = json.loads(response.content)
Can probably be simplified to `response.json()`

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/__init__.py
> +        content = json.loads(response.content)
Can probably be simplified to `response.json()`

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/__init__.py
> +            content['data'][query_name]['results'], [],
Is it not more clear to explicitly indicate that the `num_obj` should be equal to 0?

```suggestion
            num_obj, 0,
```

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/__init__.py
> +        content = json.loads(response.content)
Can probably be replaced with `response.json()`

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/__init__.py
The methods `_test_private_model` and `_test_public_model_and_private_field` are mostly copied code, except for the regex string and the error message.

I can understand that we might want to keep them separate for when these tests get more exhaustive, but on the other hand it might be nice to refactor this. For now I do not know what is better, it is just a remark.

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/test_activities.py
> +        content = json.loads(response.content)
Can be replaced with `response.json()` (similar to all other content calls)

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/test_education.py
> +            f"Query for 'educationEvent', public field 'attachments' returned an error!"
unnecessary f

2024-12-17 09:30 UTC, supertom01 commented on amelie/graphql/tests/test_news.py
> +        self.article = generate_news_article()
Maybe pass the committee explicitly instead of querying it? Since it looks like the committee is not being used

2024-12-23 12:02 UTC, Kurocon commented on amelie/settings/local.py.default
> +DEBUG_TOOLBAR = True and "test" not in sys.argv
Yes, but the `True` can be easily modified by the developer if they want to run the site in production mode, and the `'test' not in sys.argv` part is necessary to make the tests pass (debug-toolbar does not work properly during testing apparently).

I will split it out to make the difference more clear.

2024-12-23 12:11 UTC, Kurocon commented on amelie/graphql/tests/__init__.py
Agree, but I don't see a quick way to make this any better at this time

2024-12-23 12:11 UTC, Kurocon commented on amelie/graphql/tests/test_news.py
> +        self.article = generate_news_article()
Clarified why the committee is created, and switched to use `get_or_create` instead.

2024-12-23 17:19 UTC, supertom01 approved these changes

2024-12-24 14:51 UTC, Kurocon commented
New todo: Convert existing GraphQL moduels to the new authorization format.

2025-02-17 17:58 UTC, supertom01 requested changes
Just wondering if the check_authorization decorators are omitted on purpose or not.

2025-02-17 17:58 UTC, supertom01 commented on amelie/calendar/graphql.py
> +
Do we also want to add `@check_authorization` to abstract types?

2025-02-17 17:58 UTC, supertom01 commented on amelie/graphql/auth.py
> +
Add `@check_authorization` here

2025-02-17 17:58 UTC, supertom01 commented on amelie/graphql/decorators.py
> +    class FooType(DjangoObjectType):
Perhaps we should also actually add the decorator here `@check_authorization`

2025-03-03 19:18 UTC, supertom01 approved these changes

2025-03-03 21:08 UTC, supertom01 approved these changes

2025-03-03 21:08 UTC, merged