890 room duty committee rights
Inter-Actief/amelie pull request #891
Opened 2024-09-09 13:32 UTC by bramvandartel

Please add the following information to your pull request:

**Please describe what your PR is fixing**
Fix issue

**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References Inter-Actief/amelie#<issue_id>`)**
Fixes issue #890 

**Does your PR change how we process personal data, impact our [privacy document](https://www.inter-actief.utwente.nl/privacy/), or modify (one of) our data export(s)?**
no

**Does your PR include any django migrations?**
no

**Does your PR include the proper translations (did you add translations for new/modified strings)?**
no, my PR does not include translations

**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` file)?**
no, my PR does not include CSS changes

**Does your PR need external actions by for example the System Administrators? (Think about new pip packages, new (local) settings, a new regular task or cronjob, new management commands, etc.)?**
no

**Did you properly test your PR before submitting it?**
yes

2024-09-09 15:01 UTC, SimplyPancake approved these changes
Front-end and backend correctly check if a person is in the room duty committee. 
Added small util to reduce code duplication

2024-09-09 15:13 UTC, Kurocon requested changes
Looks good apart from two comments

2024-09-09 15:13 UTC, Kurocon commented on amelie/members/utils.py
> +def is_committee(request, abbreviation):
Better to add this as a helper function to the person object. That way it can simply be invoked as `request.person.is_in_committee(abbreviation)` and is reusable in other places.

2024-09-09 15:13 UTC, Kurocon commented on amelie/activities/views.py
> +@require_committee("RD")
I would prefer using a more descriptive abbreviation for the committee, like "Roomduty". Maybe also make the used abbreviation configurable via a setting.

2024-09-16 15:10 UTC, Kurocon approved these changes

2024-09-17 07:38 UTC, merged